apiVersion: v1
kind: Secret
metadata:
  name: cloudops-secrets
  namespace: cloudops
type: Opaque
stringData:
  JWT_SECRET: "replace-with-sealed-secret-or-external-secret"
  MONGODB_URI: "mongodb://mongo:27017/cloudops"
  DEMO_PASSWORD: "replace-me"
